### ISSUE TITLE
Mi9 always no sim signal

### ISSUE THREAD

**Issue by coderstory** [FlokoROM/vendor_floko#2]
After booting for a while, the sim card signal will be lost, prompting me not to insert the sim card.
If I open the system settings and enter the mobile network settings, the sim card signal will be automatically restored.and adb will disabled after reboot

use floko rom which build in 2019-05-06
use 4G network by *#*#4636#*#*

logcat and dmesg
 
https://drive.google.com/open?id=1heBPkhX9SoES-zovPDI9M4W6vdhWhnMU

**Comment by coderstory** [comment]
https://drive.google.com/open?id=1JCKJv0WWSJnaabdC0OmQdkpWBY2Ko_Rj

**Comment by coderstory** [comment]
and this  GSI
way set  ro.product.model to Mi9 in build.prop?

**Comment by lindwurm** [comment]
We have never provided any GSIs build and support officially.

if you are using https://treble.andro.plus , it may be https://github.com/folokorom-gsi (UNOFFICIAL) or phh-treble related issue.
